### ISSUE TITLE
View orders

### ISSUE THREAD

**Issue by CodeSlaughter** [FSAHotlineBling/HotlineBling#23]
As an admin I want to view a list of all orders, so that I can find specific orders to review.

Implementation
FRONT END: Upon loading app will fetch the most recent 100 orders. There will be an all orders view that shows current orders (initially fetched orders) and a button to load more. Button will be wired to api/orders route. If more orders are needed they will be concatted to already loaded orders.

BACK END: Back end will already have served an initial batch of orders. Req.session.orders will be keeping track of how many orders have been fetched. Back end (based on req.session.orders) data will fetch additional orders from database.

**Comment by bfsilva713** [comment]
Pagination not taken care of yet - will take care of if time left
