### ISSUE TITLE
Manage Changing of Order Status

### ISSUE THREAD

**Issue by SteveAksamit** [FSAHotlineBling/HotlineBling#30]
change the status of the order (Created -> Processing, Processing -> Cancelled || Completed), so that others will know what stage of the process the order is in

Created, Processing, Cancelled, Completed
Implementation
BACK-END
-Initiate status of order as CREATED to start
-Change status to PROCESSING after checkout
-Change status to CANCELLED if user cancels it
-Change status to COMPLETED once items are shipped

FRONT-END
Show status of order in user's page in all-orders view

**Comment by bfsilva713** [comment]
After checkout functionality has been built I can change status to processing
